### ISSUE TITLE
Error when using `--output FILE` argument

### ISSUE THREAD

**Issue by avetisk** [Gabriel439/bench#12]
I tried in everyway, but all I'm getting is: `bench: TemplateNotFound "default"`.

Using `bench version 1.0.2` from the OSX release.

**Comment by Gabriel439** [comment]
For some reason I cannot reproduce the issue on my end.  Here is what I tried:

```bash
$ wget https://github.com/Gabriel439/bench/releases/download/1.0.2/bench-1.0.2-x64-osx-10.11.zip
...
$ unzip bench-1.0.2-x64-osx-10.11.zip
...
$ ./bench true --output true.html  # No errors reported
benchmarking true
time                 1.615 ms   (1.593 ms .. 1.639 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 1.588 ms   (1.577 ms .. 1.600 ms)
std dev              36.25 μs   (29.06 μs .. 45.69 μs)
variance introduced by outliers: 11% (moderately inflated)

$ open true.html  # Opens results in browser
```

**Comment by avetisk** [comment]
Well, I just tried on another machine (OSX 10.12.3) and I got the same error :/

**Comment by Gabriel439** [comment]
This might be a Sierra-related error because I'm running El Capitan.  Were both of your machines running OS X Sierra?

**Comment by avetisk** [comment]
Yes, both were on macSierra.

I am pretty I can find a machine with El Capitan and run some tests on it.

I'll keep you updated :)

**Comment by Gabriel439** [comment]
Another thing worth trying is to see what happens if you build the executable on Sierra.  The error might be due to the fact that I built the executable on El Capitan, which might cause issues running on Sierra, but I was wondering if the problem would disappear if the executable were built on Sierra.

**Comment by avetisk** [comment]
Then I'll try that first.

**Comment by avetisk** [comment]
It works! 🎉 

You were right :)

So I guess you will need to publish a release per OSX versions, or at least two last ones.

**Comment by Gabriel439** [comment]
Yeah, the problem is that I don't have a Sierra machine available to build new versions and I can't upgrade my OS X machine for work-related reasons

**Comment by avetisk** [comment]
And I guess building would not be enough, you would need also to debug if the build failed etc.

**Comment by avetisk** [comment]
Would this be enough?

https://docs.travis-ci.com/user/deployment/releases/
https://docs.travis-ci.com/user/osx-ci-environment/

Although you wouldn't be able to debug on your computer.

**Comment by saulshanabrook** [comment]
I am also getting this on Sierra

**Comment by EduardoRT** [comment]
Same issue still in High Sierra.

**Comment by Gabriel439** [comment]
Is this an issue only when you use the pre-built executables or does the problem persist if you build them locally (i.e. using `stack install bench`)?

**Comment by avetisk** [comment]
As for myself it's only on the pre-built one.

**Comment by EduardoRT** [comment]
Ok, so I installed it through brew and `--output` didn't work. I uninstalled the brew version and then installed it with `stack` and it works now.

**Comment by Gabriel439** [comment]
That's weird, though.  I guess I would have expected `brew` to work unless they built the cached version on an older version of OS X

**Comment by EduardoRT** [comment]
Are you still unable to upgrade your system? I know nothing about Haskell but I'm good at following instructions.

**Comment by Gabriel439** [comment]
Yeah, I'm unable to upgrade my system at the moment (due to Nix-related issues on Sierra)

I think the correct solution is to figure out how to get `brew` to build its cached version against a newer version of Sierra because that is more trustworthy than you or me building it on our own laptops

**Comment by CJBridges** [comment]
One more data point:
MacOS Sierra (10.12.6)

`brew uninstall bench && brew install --build-from-source bench`

```
$ bench true --output foo.html
benchmarking true
time                 2.340 ms   (2.305 ms .. 2.386 ms)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 2.291 ms   (2.262 ms .. 2.313 ms)
std dev              79.65 μs   (66.37 μs .. 104.2 μs)
variance introduced by outliers: 19% (moderately inflated)

bench: TemplateNotFound "default"
```

Using `stack install bench` did result in a copy of `bench` that would properly output HTML, but it was running `bench 1.0.2` instead of the `1.0.6` that `brew install` did.

**Comment by ericbn** [comment]
I'm using El Capitan and installed bench with `brew install bench` (so not from sources). I'm getting the `bench: TemplateNotFound "default"` error.

**Comment by Gabriel439** [comment]
Okay, I think I've figured out the problem.

**Short explanation:** This will not work with a binary distribution of `bench` nor will it work with `brew` because the binary contains a hard-coded runtime reference to a template located on the machine it was built on.

**Long explanation:**

`bench` depends on the Haskell `criterion` library to provide the actual benchmarking functionality (`bench` is a very thin command-line wrapper around `criterion`).  `criterion` uses `cabal`'s support for distributing data files (i.e. files that are not object code) to install the `default` template on the host system where the binary is built.  These data files are *not* included in the binary but are instead installed underneath the user's `~/.cabal/share` directory

This explains all of the observed behavior in this thread.  The consistent theme is that if you build the `bench` binary locally (using either `cabal` or `stack`) then the `--output` option works because the default template was installed as part of the build process.  If you use a binary distribution of `bench` (such as from the releases page or `brew`) then the binary fails

The version of OS X doesn't matter.  That was a mistaken diagnosis on my part.

This is the same issue as https://github.com/bos/criterion/issues/45

I will open an issue upstream with `criterion` to see if they can suggest a solution to this problem.  In the short term the work-around is that you must build `bench` locally (using either `cabal`, `stack`, or Nix)

**Comment by ericbn** [comment]
> the binary contains a hard-coded runtime reference to a template located on the machine it was built on.

Can't the auxiliary files be included in the release archive (along with the binaries)? For homebrew, for example, we could change the installation script to copy those auxiliary files from the release archive to the required directories. Looks like the destination would be `~/.cabal/share`.

**Comment by Gabriel439** [comment]
See the upstream issue: https://github.com/bos/criterion/issues/45

This may be fixable with a cabal flag to optionally embed the assets into the executable

**Comment by Gabriel439** [comment]
Alright, I built a `bench` executable using `stack` for OS X with the option set to embed the assets into the binary, which you can download here:

[bench.tar.gz](https://github.com/Gabriel439/bench/files/1523164/bench.tar.gz)

Could somebody test on their system that this executable works correctly with the `--output` flag?  If it does then I'll update the release page to use this

**Comment by ericbn** [comment]
Works for me! 🎉

I'm under Mac OS X 10.11.6 El Capitan

**Comment by EduardoRT** [comment]
Works for me too! 😍

MacOS 10.13.1 High Sierra

**Comment by Gabriel439** [comment]
Alright, I've uploaded this relocatable executable as the latest release candidate and will continue to build this way for future releases: https://github.com/Gabriel439/bench/releases/tag/1.0.7-rc1

I'll mark this complete.  Thanks everybody for being patient

**Comment by sergeevabc** [comment]
Windows user also suffers from ```bench.exe: TemplateNotFound "default"``` on v1.0.2.

**Comment by Gabriel439** [comment]
@sergeevabc: I just updated the 1.0.8 release with a windows build that is built in the same way.  Let me know if you still run into the issue when using it: 

https://github.com/Gabriel439/bench/releases/tag/1.0.8
