### ISSUE TITLE
Build failure: turtle-1.3.1 must match >=1.2.5 && <1.3 (latest applicable is 1.2.8)

### ISSUE THREAD

**Issue by danielyli** [Gabriel439/bench#13]
I'm trying to build `bench` on macOS 10.12.3 Sierra.  I installed `stack` 1.3.2 (via Homebrew) and followed the instructions to `stack setup` and `stack install bench`.  `stack setup` completed successfully, but `stack install bench` fails with the following message:

```
In the dependencies for bench-1.0.2:
    turtle-1.3.1 must match >=1.2.5 && <1.3 (latest applicable is 1.2.8)
```

I've copied the entire output below.

I'm a complete Haskell beginner.  (In fact, this is my first time building a Haskell package.)  Is this something on my end that I'm doing wrong with the build?

```
$ stack setup
Using latest snapshot resolver: lts-8.4
Writing implicit global project config file to: /Users/dd/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Downloaded lts-8.4 build plan.
Fetched package index.
Populated index cache.
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.0.2.
Installed GHC.
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

$ stack install bench

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for bench-1.0.2:
    turtle-1.3.1 must match >=1.2.5 && <1.3 (latest applicable is 1.2.8)

Plan construction failed.

```

**Comment by Gabriel439** [comment]
First, I'll explain the error, why it happened, and how to fix it.

## Explanation

`stack` uses Stackage, which is a curated package set of packages that build together and it's versioned using "resolver"s.  When `stack` picks a resolver, like in this line:

```
Using latest snapshot resolver: lts-8.4
```

... it's picking a specific version of the curated package set.  You can see which versions it picks for each package in the set by visiting:

https://www.stackage.org/lts-8.4/cabal.config

Some packages on Hackage are in this curated package set and other packages are not.  For example, `turtle` is in the curated package set and is pinned to version `1.3.1` (which you can see by visiting the above link and searching for `turtle`).  However, `bench` is not part of the curated package set and therefore not guaranteed to build against the dependencies that `stack` selects.

What happened is that `bench` has a dependency on `turtle` which you can view if you visit the Hackage page for `turtle` here:

https://hackage.haskell.org/package/bench

Specifically the dependency is of the form:

```
 turtle >=1.2.5 && <1.3
```

... which you can read as saying that `bench` depends on any `turtle` version greater than version `1.2.5` or less than `1.3`.  The reason for the `< 1.3` upper bound on the `turtle` dependency is due to the Hackage package versioning policy:

https://pvp.haskell.org/

... which says that any change to the second version number of a package (i.e. the `2` in `1.2.5`) indicates a breaking API change.  At the time `bench` was released the latest `turtle` version was `1.2.5`, so an upper bound of `1.3.` was necessary to guard against breaking changes until `bench` had been tested against `turtle` versions of `1.3` or higher.

So when you try to `stack install` a package outside of the Stackage curated package set, `stack` tries to go ahead and build it anyway, even if dependency resolution might fail.  That's what happened in your case: `stack install bench` went ahead and attempted to resolve the dependencies for `bench` and gave up because `bench` required a `turtle` version earlier than `1.3` but Stackage pins `turtle` to `1.3.1`.  This is what `stack` meant when it printed this line:

```
In the dependencies for bench-1.0.2:
    turtle-1.3.1 must match >=1.2.5 && <1.3 (latest applicable is 1.2.8)
```

## Solution 1 - Use a different version of `turtle`

`stack` is flexible, though, and lets you deviate from the curated package versions if you want to.  The only risk in doing so is that newer versions of packages have not been tested/curated to build against the other packages in Stackage, but in practice it's usually completely harmless to change a few dependencies if you know what you're doing.

The way you can specify a dependency override is to create a `stack.yaml` file in your current directory with the following contents:

```
resolver: lts-8.4
extra-deps:
- turtle-1.2.8
```

That tells `stack` to still use all the packages in the `lts-8.4` resolver by default, with the exception of `turtle`, where we want to override the `turtle` version to `1.2.8`

## Solution 2 - I upload the latest version of `bench` to Hackage

The Hackage release of `bench` is actually quite old and since then `bench` has had a few feature improvements and has been tested against newer versions of `turtle`.  For example, `bench` has a new upper bound of `turtle < 1.4` on `master`, which you can find here:

https://github.com/Gabriel439/bench/blob/master/bench.cabal#L33

However, I had forgotten to upload `bench` to Hackage, which is why the older upper bound is still there when you tried to build.

So if I upload `bench` to Hackage (which I will do after I finish writing this) then `stack install bench` would "just work" without any package overrides once it picks up the latest version of `bench` on Hackage.

## Solution 3 - I add `bench` to Stackage

I can also add `bench` to Stackage so that its dependencies get automatically checked and I get notified if `bench` doesn't build against other packages in Stackage (like `turtle`).  This is something I will also do, in addition to uploading `bench` to Hackage.

**Comment by Gabriel439** [comment]
Alright, I uploaded the latest version of `bench` to Hackage, which the new upper bound on `turtle`: https://hackage.haskell.org/package/bench-1.0.3

I believe it takes about 30 minutes for `stack` to pick up Hackage updates, so after that `stack install bench` should work

I will continue to work on adding `bench` to Stackage

**Comment by danielyli** [comment]
Your explanation is amazing—thank you for the comprehensive learning experience!  It's actually pretty great that Stack can not only specify reproducible builds and dependencies, but it also gives very helpful error messages when dependencies do mismatch.

Yup, `stack install bench` is working now.  Thanks!

**Comment by Gabriel439** [comment]
You're welcome! :)
