### ISSUE TITLE
Redirection in a command causes bench to fail

### ISSUE THREAD

**Issue by genevera** [Gabriel439/bench#22]
When I try to bench a command using redirection that otherwise works, bench fails.  

e.g.
```bash
$ uniq -c <(sort /tmp/l.txt)
  19 "AcceptVpcPeeringConnection"
   1 "AssociateDhcpOptions"
   1 "AttachInternetGateway"
   1 "AttachVpnGateway"
   1 "CreateDBInstance"
   1 "CreateDBSubnetGroup"
  99 "CreateLoadBalancer"
 585 "CreateNetworkInterface"
   4 "CreateRouteTable"
  94 "CreateSecurityGroup"
   6 "CreateSubnet"
   1 "CreateTags"
  98 "CreateTargetGroup"
   1 "CreateVpc"
  20 "CreateVpcPeeringConnection"
  63 "ModifyTargetGroup"
   2 "ModifyVpcAttribute"
1235 "RunInstances"
```

```bash
$ bench 'uniq -c <(sort /tmp/l.txt)'
benchmarking uniq -c <(sort /tmp/l.txt)
bench: ShellFailed {shellCommandLine = "uniq -c <(sort /tmp/l.txt)", shellExitCode = ExitFailure 2}
```

**Comment by Gabriel439** [comment]
Sorry for the delay.  It looks like this is due to https://github.com/Gabriel439/bench/commit/e233c2b0aa7d1e040da2c100a7cbfbfb3e242770 (`bench` closes standard input), which is in turn due to https://github.com/Gabriel439/bench/issues/14

Note that in this case you can work around this limitation by piping the command instead of using redirection:

```
$ bench 'sort /tmp/l.txt | uniq -c'
benchmarking sort /tmp/l.txt | uniq -c
time                 7.441 ms   (7.189 ms .. 7.761 ms)
                     0.982 R²   (0.963 R² .. 0.993 R²)
mean                 7.933 ms   (7.757 ms .. 8.163 ms)
std dev              603.4 μs   (432.0 μs .. 865.8 μs)
variance introduced by outliers: 43% (moderately inflated)
```

However, if there are other scenarios where you can't work around the issue in this way then I can add a flag to allow enabling/disabling standard input

**Comment by genevera** [comment]
Hi sorry for the delayed response - thank you for the suggestion!  Ultimately I wound up wrapping the commands in a shell script.  That being said, if it's not too much trouble that would be a nice feature.
